#!/bin/bash
set -e

OS=$(uname -o | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

if [ "$OS" != "linux" ]; then
    echo "Unexpected OS $OS. Please, try it on Linux." >&2
    exit 1
fi

for IMG in hmmer-builder hmmpress h3master h3worker; do
    echo "-- Building $IMG on $OS/$ARCH"
    TAG="quay.io/microbiome-informatics/$IMG:$ARCH"
    (cd $IMG && podman build -t "$TAG" --arch "$ARCH" --os "$OS" .)
    echo
    echo
done
