#!/bin/bash
set -e

OS=$(uname -o | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

if [ "$OS" != "linux" ]; then
    echo "Unexpected OS $OS. Please, try it on Linux." >&2
    exit 1
fi

for IMG in hmmer-builder hmmpress h3master h3worker; do
    echo "-- Pushing $IMG on $OS/$ARCH"
    TAG="quay.io/microbiome-informatics/$IMG:$ARCH"
    podman push --format v2s2 "$TAG" --arch "$ARCH" --os "$OS"
done
