FROM docker.io/alpine
LABEL maintainer="danilo.horta@pm.me"
ARG TARGETARCH
COPY --from=quay.io/microbiome-informatics/hmmer-builder:$TARGETARCH /hmmer/src/hmmpgmd /usr/local/bin/hmmpgmd
COPY h3worker /usr/local/bin/h3worker
COPY healthcheck /usr/local/bin/healthcheck
RUN chmod 0755 /usr/local/bin/h3worker
RUN chmod 0755 /usr/local/bin/healthcheck
ENTRYPOINT ["/usr/local/bin/h3worker"]
