FROM docker.io/alpine
LABEL maintainer="danilo.horta@pm.me"
ARG TARGETARCH
COPY --from=quay.io/microbiome-informatics/hmmer-builder:$TARGETARCH /hmmer/src/hmmpress /usr/local/bin/hmmpress
RUN chmod 0755 /usr/local/bin/hmmpress
ENTRYPOINT ["/usr/local/bin/hmmpress"]
CMD ["-h"]
